# Generated by Django 4.1 on 2023-12-15 18:42

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('date', django.contrib.postgres.fields.ranges.DateRangeField(default=['2023-01-01', '2023-01-03'])),
            ],
        ),
        migrations.AddIndex(
            model_name='first',
            index=models.Index(fields=['fname', 'date'], name='systemapp_f_fname_19f4bd_idx'),
        ),
    ]
