# Generated by Django 4.1 on 2023-12-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='second',
            index=models.Index(fields=['fname'], name='systemapp_s_fname_019e1a_idx'),
        ),
    ]
