# Generated by Django 4.1 on 2023-12-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0001_squashed_0002_second_second_systemapp_s_fname_019e1a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='second',
            name='lname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='second',
            index_together={('fname', 'lname')},
        ),
    ]
