# Generated by Django 4.1 on 2023-12-23 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_second_lname_alter_second_index_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=200)),
                ('people_in', models.IntegerField()),
                ('people_out', models.IntegerField()),
                ('recordated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='second',
            name='systemapp_s_fname_019e1a_idx',
        ),
        migrations.AddIndex(
            model_name='second',
            index=models.Index(fields=['fname', 'lname'], name='systemapp_s_fname_658083_idx'),
        ),
    ]
